apiVersion: apps/v1
kind: Deployment
metadata:
  name: synergychat-api
  labels:
    app: synergychat-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synergychat-api
  template:
    metadata:
      labels:
        app: synergychat-api
    spec:
      containers:
        - name: synergychat-api
          image: lanecwagner/synergychat-api:latest
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - name: synergychat-api-volume
              mountPath: /persist
          env:
            - name: API_PORT
              valueFrom:
                configMapKeyRef:
                  key: API_PORT
                  name: synergychat-api-configmap
            - name: API_DB_FILEPATH
              valueFrom:
                configMapKeyRef:
                  key: API_DB_FILEPATH
                  name: synergychat-api-configmap
      volumes:
        - name: synergychat-api-volume
          persistentVolumeClaim:
            claimName: synergychat-api-pvc

