apiVersion: apps/v1
kind: Deployment
metadata:
  name: synergychat-crawler
  labels:
    app: synergychat-crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synergychat-crawler
  template:
    metadata:
      labels:
        app: synergychat-crawler
    spec:
      containers:
        - name: synergychat-crawler
          image: lanecwagner/synergychat-crawler:latest
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
          envFrom:
            - configMapRef:
                name: synergychat-crawler-configmap
